bundler_args: --binstubs
sudo: false
language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
      - noel@peden.biz
    on_success: always
env:
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1
  # - RAILS_VERSION=5.2
  - RAILS_VERSION=6.0.0.rc2
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.1
  - 2.6.3
before_install:
  - gem update bundler
script:
  spec/ci.rb
